Spanish translation
SamAmco/track-and-graph pull request #81
Opened 2021-03-22 17:50 UTC by sguinetti

I would like to translate this application into Spanish. So I made this PR trying to explain the topic of traces and how to plot them. Thanks in advance.

2021-03-23 18:37 UTC, SamAmco commented
This looks awesome, thanks for doing this. I will have to google translate it back to english and make sure it's all close enough correct, but I will try and do this soon and get back to you.

2021-03-27 18:06 UTC, SamAmco requested changes
I had a couple of comments on this but overall it looks really good. I have one more string I'm adding in a new feature that's not on the master branch yet. I have a button you can hold down to preview the graph on the graph setup page. The button has the text "Hold to preview" .. Maybe you can just give me the best translation for that here?

2021-03-30 21:10 UTC, sguinetti commented on app/src/main/res/values-es/strings.xml
> +    <string name="add_feature">Añade líneas:</string>
Interesting, then it would be "añadir trazas" because you mention by the tracks you have explained.

2021-03-30 21:11 UTC, sguinetti commented on app/src/main/res/values-es/strings.xml
> +    <string name="no_features_hint">Toca el icono + para empezar a registrar algo.</string>
I would keep it. Because traces need to be registered, while literal translation about "posting" has a different meaning.

2021-03-30 21:13 UTC, sguinetti commented on app/src/main/res/values-es/strings.xml
> +    <string name="faq_1">¿Cómo empiezo a trazar algo?</string>
Yes. Otherwise it would bad translate as "graficar".

2021-03-30 21:14 UTC, sguinetti commented on app/src/main/res/values-es/strings.xml
> +    <string name="faq_2">¿Cómo importo/exporto lo que he trazado?</string>
Similar to "track". The translation is about "trazas" and its verb "trazar".

2021-03-30 21:15 UTC, sguinetti commented on app/src/main/res/values-es/strings.xml
> +    <string name="tutorial_text_3">Utiliza los grupos de trazas para investigar los datos de varios grupos de trazas.</string>
I see, so it is a confusion. I translated as _Utiliza los grupos de **gráficos** para investigar los datos de varios grupos de trazas._ Right?

2021-04-11 11:47 UTC, merged

2021-04-11 12:09 UTC, SamAmco commented
Ok thanks again for doing this. I have merged your PR and fixed up the issues locally. This will be in the next release :)

2021-04-17 19:34 UTC, SamAmco commented
I forgot to mention regarding this that I was un-able to add your fastlane files. Basically the short description was too long (as per the google play store guidelines) but also fastlane seems to be quite a pain and won't fallback to English if the Spanish version is not supplied. This means I would need all the screenshots and all text, a full copy of everything that's in the English fastlane files. I don't expect you to create this, although you can if you like. I just took out the spanish store page translation for now.

2021-05-23 18:57 UTC, SamAmco commented
@allcontributors bot please add @sguinetti for translation